Watching for file changes with StatReloader
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2489
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2489
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2489
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2489
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Internal Server Error: /web_chat_bot/
Traceback (most recent call last):
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/views.py", line 23, in get
    return HttpResponse(chat_req_get(request))
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/web_chat_logic.py", line 23, in chat_req_get
    return user_has_position(ip, user_position, ui)
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/web_chat_logic.py", line 121, in user_has_position
    return start_chat(help_type=True)
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/web_chat_logic.py", line 58, in start_chat
    return json.dumps({'btn_text': btn_text, "help_text": text_out}, ensure_ascii=False)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
"GET /web_chat_bot/?us_in=%D0%92%D0%B5%D1%80%D0%BD%D1%83%D1%82%D1%8C%D1%81%D1%8F%20%D0%B2%20%D0%BC%D0%B5%D0%BD%D1%8E HTTP/1.1" 500 17739
Internal Server Error: /web_chat_bot/
Traceback (most recent call last):
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/views.py", line 23, in get
    return HttpResponse(chat_req_get(request))
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/web_chat_logic.py", line 23, in chat_req_get
    return user_has_position(ip, user_position, ui)
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/web_chat_logic.py", line 121, in user_has_position
    return start_chat(help_type=True)
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/web_chat_logic.py", line 58, in start_chat
    return json.dumps({'btn_text': btn_text, "help_text": text_out}, ensure_ascii=False)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type StartMessage is not JSON serializable
"GET /web_chat_bot/?us_in=%D0%92%D0%B5%D1%80%D0%BD%D1%83%D1%82%D1%8C%D1%81%D1%8F%20%D0%B2%20%D0%BC%D0%B5%D0%BD%D1%8E HTTP/1.1" 500 17747
Internal Server Error: /web_chat_bot/
Traceback (most recent call last):
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bequite/PycharmProjects/HelpBot/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/views.py", line 23, in get
    return HttpResponse(chat_req_get(request))
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/web_chat_logic.py", line 23, in chat_req_get
    return user_has_position(ip, user_position, ui)
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/web_chat_logic.py", line 122, in user_has_position
    return start_chat(help_type=True)
  File "/home/bequite/PycharmProjects/HelpBot/help_bot/web_chat_logic.py", line 59, in start_chat
    return json.dumps({'btn_text': btn_text, "help_text": text_out}, ensure_ascii=False)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type StartMessage is not JSON serializable
"GET /web_chat_bot/?us_in=%D0%92%D0%B5%D1%80%D0%BD%D1%83%D1%82%D1%8C%D1%81%D1%8F%20%D0%B2%20%D0%BC%D0%B5%D0%BD%D1%8E HTTP/1.1" 500 17747
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2506
